DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS film_user;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS genre
(
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(200)
);

CREATE TABLE IF NOT EXISTS film
(
    film_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(200),
    description  CHARACTER LARGE OBJECT,
    release_date date,
    duration     int,
    mpa          tinyint
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  int,
    genre_id int,
    CONSTRAINT fk_film FOREIGN KEY (film_id) REFERENCES film (film_id),
    CONSTRAINT fk_genre FOREIGN KEY (genre_id) REFERENCES genre (genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(200),
    login    varchar(200),
    birthday date,
    email    varchar(200)
);

CREATE TABLE IF NOT EXISTS film_user
(
    film_id int,
    user_id int,
    CONSTRAINT fk_film_user FOREIGN KEY (film_id) REFERENCES film (film_id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    sender_id     int,
    recipient_id  int,
    status_accept boolean,
    CONSTRAINT fk_sender FOREIGN KEY (sender_id) REFERENCES users (user_id),
    CONSTRAINT fk_recipient FOREIGN KEY (recipient_id) REFERENCES users (user_id)
);